# Generated by Django 2.0.1 on 2018-10-30 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='configuracionBDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respaldo', models.BooleanField()),
                ('periodo', models.CharField(max_length=1)),
                ('ultima_respaldo', models.DateField(default=datetime.date(2018, 10, 30))),
                ('ultima_importacion', models.DateField(default=datetime.date(2018, 10, 30))),
                ('ultima_restauracion', models.DateField(default=datetime.date(2018, 10, 30))),
            ],
        ),
    ]
