# Generated by Django 2.0.1 on 2018-11-05 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name=datetime.date(2018, 11, 5))),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='configuracionBDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respaldo', models.IntegerField()),
                ('periodo', models.CharField(max_length=1)),
                ('ultima_respaldo', models.DateField(verbose_name=datetime.date(2018, 11, 5))),
                ('ultima_importacion', models.DateField(verbose_name=datetime.date(2018, 11, 5))),
                ('ultima_restauracion', models.DateField(verbose_name=datetime.date(2018, 11, 5))),
            ],
        ),
    ]
