# Generated by Django 2.0.1 on 2018-11-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionbda',
            name='ultima_importacion',
        ),
        migrations.RemoveField(
            model_name='configuracionbda',
            name='ultima_respaldo',
        ),
        migrations.RemoveField(
            model_name='configuracionbda',
            name='ultima_restauracion',
        ),
    ]
