# Generated by Django 2.0.1 on 2018-10-30 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_respaldo', models.DateField(verbose_name=datetime.date(2018, 10, 30))),
                ('ultima_importacion', models.DateField(verbose_name=datetime.date(2018, 10, 30))),
                ('ultima_restauracion', models.DateField(verbose_name=datetime.date(2018, 10, 30))),
            ],
        ),
        migrations.RemoveField(
            model_name='configuracionbda',
            name='ultima_importacion',
        ),
        migrations.RemoveField(
            model_name='configuracionbda',
            name='ultima_respaldo',
        ),
        migrations.RemoveField(
            model_name='configuracionbda',
            name='ultima_restauracion',
        ),
    ]
