# Generated by Django 2.0.1 on 2018-10-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20181030_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionbda',
            name='respaldo',
            field=models.IntegerField(),
        ),
    ]
