# Generated by Django 2.0.1 on 2018-11-05 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20181105_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionbda',
            name='uitima_exportacion',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='configuracionbda',
            name='ultima_importacion',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='configuracionbda',
            name='ultimo_respaldo',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
