# Generated by Django 2.0.1 on 2018-11-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20181105_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionbda',
            name='uitima_exportacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionbda',
            name='ultima_importacion',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionbda',
            name='ultimo_respaldo',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
