# Generated by Django 2.0.1 on 2018-11-21 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20181114_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraTransaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('accion', models.CharField(max_length=80)),
                ('tabla', models.CharField(blank=True, max_length=80)),
                ('campo', models.CharField(blank=True, max_length=80)),
                ('registro', models.CharField(blank=True, max_length=80)),
                ('valor_anterior', models.CharField(blank=True, max_length=80)),
                ('valor_actual', models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
