# Generated by Django 2.0.5 on 2013-01-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('nombre', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('tematica', models.CharField(default='', max_length=50)),
                ('fecha_inicio', models.DateField(default=None)),
                ('fecha_final', models.DateField(default=None)),
                ('participantes', models.ManyToManyField(to='personas.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=None)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], max_length=9)),
                ('asistentes', models.ManyToManyField(to='personas.Persona')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.Grupo')),
            ],
        ),
    ]
