# Generated by Django 2.0.1 on 2018-04-04 20:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('Solicitud de Cita', 'Solicitud de Cita'), ('Triaje y Evaluación', 'Triaje y Evaluación'), ('Contención', 'Contención'), ('Notificación Recibida', 'Notificación Recibida'), ('Notificación Enviada', 'Notificación Enviada'), ('Remisión de Informe', 'Remision de Informe'), ('Visita Domiciliaria', 'Visita Domiciliaria'), ('Orientación', 'Orientación'), ('Audiencia', 'Audiencia'), ('Prueba Anticipada', 'Prueba Anticipada'), ('Referencia a Centro de Salud', 'Referencia a Centro de Salud'), ('Carta de Culminación', 'Carta de Culminación'), ('Llamada Telefónica', 'Llamada Telefónica'), ('Taller', 'Taller')], max_length=28)),
                ('fecha', models.DateTimeField(default=datetime.datetime.today)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('nro_expediente', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('procedencia', models.CharField(choices=[('Control 1', 'Control 1'), ('Control 2', 'Control 2'), ('Control 3', 'Control 3'), ('Juicio 1', 'Juicio 1'), ('Juicio 2', 'Juicio 2'), ('Ejecución', 'Ejecución'), ('Carora Ordinario', 'Carora Ordinario')], max_length=16)),
                ('solicitud', models.CharField(choices=[('Evaluación Psicológica', 'Evaluación Psicológica'), ('Evaluación Social', 'Evaluación Social'), ('Evaluación Psico-Social', 'Evaluación Psico-Social'), ('Triaje', 'Triaje'), ('Taller', 'Taller'), ('Orientación', 'Orientación'), ('Prueba Anticipada', 'Prueba Anticipada')], max_length=23)),
                ('delito', models.CharField(choices=[('Violencia Psicológica', 'Violencia Psicológica'), ('Acoso u Hostigamiento', 'Acoso u Hostigamiento'), ('Amenaza', 'Amenaza'), ('Violencia Física', 'Violencia Física'), ('Violencia Física Agravada', 'Violencia Física Agravada'), ('Violencia Sexual', 'Violencia Sexual'), ('Acto Carnal con Víctima Vulnerable', 'Acto Carnal con Víctima Vulnerable'), ('Actos Lascivos', 'Actos Lascivos'), ('Prostitución Forzada', 'Prostitución Forzada'), ('Esclavitud Sexual', 'Esclavitud Sexual'), ('Acoso Sexual', 'Acoso Sexual'), ('Violencia Laboral', 'Violencia Laboral'), ('Violencia Patrimonial y Económica', 'Violencia Patrimonial y Económica'), ('Violencia Obstétrica', 'Violencia Obstetrica'), ('Esterilización Forzada', 'Esterilización Forzada'), ('Ofensa Pública', 'Ofensa Pública'), ('Violencia Institucional', 'Violencia Institucional'), ('Tráfico Ilícito de Niñas, Adolescentes y Mujeres', 'Tráfico Ilicito de Niñas, Adolescentes y Mujeres'), ('Trata de Mujeres, Niñas y Adolescentes', 'Trata Mujeres, Niña y Adolescentes'), ('Femicidio', 'Femicidio'), ('Femicidio Agravado', 'Femicidio Agravado'), ('Inducción al Suicidio', 'Inducción al Suicidio'), ('Obligación de Aviso', 'Obligación de Aviso'), ('Obligación de Trámites de Denuncia', 'Obligación de Trámites de Denuncia'), ('Obligación de Implementación de Correctivos', 'Obligación de Implementación de Correctivos'), ('Otros', 'Otros')], max_length=50)),
                ('fecha_ingreso', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Culminado', 'Culminado')], max_length=9)),
                ('personas', models.ManyToManyField(to='personas.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Triaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genograma_imputado', models.TextField()),
                ('genograma_victima', models.TextField()),
                ('testimonio_imputado', models.TextField()),
                ('testimonio_victima', models.TextField()),
                ('impresion_diagnostica', models.TextField()),
                ('modalidad', models.CharField(choices=[('Orientación', 'Orientación'), ('Evaluación', 'Evaluación'), ('Remisión Externa', 'Remisión Externa')], max_length=16, verbose_name='Modalidad de Intervención')),
                ('observaciones', models.TextField()),
                ('derivacion', models.CharField(choices=[('Asesoría Jurídica', 'Asesoría Jurídica'), ('Trabajo Social', 'Trabajo Social'), ('Medicina', 'Medicina'), ('Psicología', 'Psicología'), ('Educación', 'Educación')], max_length=17, verbose_name='Derivacion a equipo interdisciplinario')),
                ('proxima_cita', models.DateField()),
                ('atendido_por', models.CharField(max_length=50)),
            ],
        ),
    ]
