# Generated by Django 2.0.1 on 2018-04-05 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triaje',
            name='causa',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='causas.Causa'),
        ),
    ]
