# Generated by Django 2.0.1 on 2018-04-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0002_triaje_causa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triaje',
            name='proxima_cita',
            field=models.DateField(default=None),
        ),
    ]
