# Generated by Django 2.0.5 on 2018-05-12 23:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0005_auto_20180412_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=28)),
                ('fecha', models.DateTimeField(default=datetime.datetime.today)),
                ('realizado_por', models.CharField(max_length=50)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causas.Causa')),
            ],
        ),
        migrations.AlterField(
            model_name='triaje',
            name='proxima_cita',
            field=models.DateField(default=datetime.date(2018, 5, 19)),
        ),
    ]
