# Generated by Django 2.0.5 on 2018-05-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0006_auto_20180512_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triaje',
            name='genograma_imputado',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='genograma_victima',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='impresion_diagnostica',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='testimonio_imputado',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='testimonio_victima',
            field=models.TextField(blank=True),
        ),
    ]
