# Generated by Django 2.0.5 on 2013-01-01 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0007_auto_20180512_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triaje',
            name='proxima_cita',
            field=models.DateField(default=datetime.date(2013, 1, 8)),
        ),
    ]
