# Generated by Django 2.0.5 on 2018-05-14 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0008_auto_20130101_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Culminado', 'Culminado')], default='Pendiente', max_length=9),
        ),
        migrations.AlterField(
            model_name='causa',
            name='procedencia',
            field=models.CharField(choices=[('Control 1', 'Control 1'), ('Control 2', 'Control 2'), ('Control 3', 'Control 3'), ('Juicio 1', 'Juicio 1'), ('Juicio 2', 'Juicio 2'), ('Ejecución', 'Ejecución'), ('Otros Tribunales', 'Otros Tribunales')], max_length=16),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='proxima_cita',
            field=models.DateField(default=datetime.date(2018, 5, 20)),
        ),
    ]
