# Generated by Django 2.0.1 on 2018-11-06 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0014_auto_20181105_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triaje',
            name='proxima_cita',
            field=models.DateField(default=datetime.date(2018, 11, 13)),
        ),
    ]
