# Generated by Django 2.0.1 on 2018-11-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0015_auto_20181106_1046'),
        ('causas', '0015_auto_20181106_1103'),
    ]

    operations = [
    ]
