# Generated by Django 2.0.1 on 2018-11-12 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0017_auto_20181108_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triaje',
            name='proxima_cita',
            field=models.DateField(default=datetime.date(2018, 11, 19)),
        ),
    ]
