# Generated by Django 2.0.1 on 2018-11-13 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0018_auto_20181112_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triaje',
            name='proxima_cita',
            field=models.DateField(default=datetime.date(2018, 11, 20)),
        ),
    ]
