# Generated by Django 2.0.1 on 2018-11-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0019_auto_20181113_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='causa',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='causa',
            name='is_editing',
            field=models.CharField(default=0, max_length=9),
        ),
    ]
