# Generated by Django 2.0.1 on 2018-11-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0019_auto_20181113_0530'),
        ('causas', '0020_auto_20181113_1035'),
        ('causas', '0019_auto_20181113_0601'),
    ]

    operations = [
    ]
