# Generated by Django 2.0.1 on 2018-11-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0022_auto_20181114_0338'),
        ('causas', '0021_merge_20181113_2149'),
    ]

    operations = [
    ]
