# Generated by Django 2.0.1 on 2018-11-21 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0024_auto_20181120_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triaje',
            name='proxima_cita',
            field=models.DateField(default=datetime.date(2018, 11, 28)),
        ),
    ]
