# Generated by Django 2.0.1 on 2018-11-06 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=30)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='preguntas',
            field=models.ManyToManyField(through='usuarios.PreguntaUsuario', to='usuarios.Pregunta'),
        ),
    ]
