# Generated by Django 2.0.1 on 2018-04-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20180404_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.CharField(max_length=9, unique=True, verbose_name='Identificación'),
        ),
    ]
