# Generated by Django 2.0.1 on 2018-11-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20181108_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_audit',
            field=models.BooleanField(default=False, verbose_name='Auditor'),
        ),
    ]
