# Generated by Django 2.0.1 on 2018-11-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20181112_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
