# Generated by Django 2.0.1 on 2018-11-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20181113_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='usuario',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
