# Generated by Django 2.0.1 on 2018-11-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20181113_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='version',
        ),
        migrations.AddField(
            model_name='usuario',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
