# Generated by Django 2.0.1 on 2018-11-14 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_bitacoraacceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacoraacceso',
            name='hora',
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='fecha',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
