# Generated by Django 2.0.1 on 2018-04-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(default='', max_length=30)),
                ('apellido', models.CharField(default='', max_length=30)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=9)),
                ('lugar_de_nacimiento', models.CharField(default='', max_length=50)),
                ('fecha_de_nacimiento', models.DateField(default=None)),
                ('ci', models.PositiveIntegerField(default=0, primary_key=True, serialize=False, verbose_name='Cédula de Identidad')),
                ('estado_civil', models.CharField(choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Viudo(a)', 'Viudo(a)'), ('Divorciado(a)', 'Divorciado(a)')], max_length=13)),
                ('nacionalidad', models.CharField(default='', max_length=30)),
                ('grado_de_institucion', models.CharField(choices=[('Sin estudios', 'Sin estudios'), ('Primaria', 'Primaria'), ('Bachiller', 'Bachiller'), ('Técnico Medio', 'Técnico Medio'), ('Universitario', 'Universitario')], max_length=30)),
                ('direccion', models.CharField(default='', max_length=50)),
                ('telefono', models.CharField(default='', max_length=12)),
                ('ocupacion', models.CharField(default='', max_length=20)),
                ('direccion_trabajo', models.CharField(default='', max_length=50)),
                ('condicion', models.CharField(choices=[('Imputado', 'Imputado'), ('Víctima', 'Víctima')], max_length=8, verbose_name='Condición')),
            ],
        ),
    ]
