# Generated by Django 2.0.5 on 2018-05-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='condicion',
            field=models.CharField(blank=True, choices=[('Imputado', 'Imputado'), ('Víctima', 'Víctima')], max_length=8, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion_trabajo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Viudo(a)', 'Viudo(a)'), ('Divorciado(a)', 'Divorciado(a)')], max_length=13),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='grado_de_institucion',
            field=models.CharField(blank=True, choices=[('Sin estudios', 'Sin estudios'), ('Primaria', 'Primaria'), ('Bachiller', 'Bachiller'), ('Técnico Medio', 'Técnico Medio'), ('Universitario', 'Universitario')], max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='lugar_de_nacimiento',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ocupacion',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
